name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/setup@v2
        with:
          cache: true
          runtime: node@22
      - run: pnpm lint
      - run: pnpm build
